### ISSUE TITLE
Example please

### ISSUE THREAD

**Issue by heartily0421** [hcq0618/Unity-ImageLoader#1]
Hello, I found your project is very promising. 
Can you please provide any working sample?

**Comment by hcq0618** [comment]
i have no time to do it , the source code is readability，and u can easy to use

**Comment by heartily0421** [comment]
I'm using in Windows.
It throw GetMaxMemory not implemented Exception message.
At Devices.cs, you coded only android, it needs modificaton like below bolded italic code.

-code start-
public static long GetMaxMemory()
{
  #if UNITY_ANDROID
            using (AndroidJavaClass runtime = new AndroidJavaClass("java.lang.Runtime"))
            {
                using (AndroidJavaObject run = runtime.CallStatic<AndroidJavaObject>("getRuntime"))
                {
                    long maxMemory = run.Call<long>("maxMemory");
                    return maxMemory;
                }
            }
  _**#elif (UNITY_EDITOR_WIN || UNITY_STANDALONE_WIN)
            return SystemInfo.systemMemorySize;
            //throw new NotImplementedException();**
  #endif_
}
-code end-

I hope it will be the end of error.

**Comment by hcq0618** [comment]
I've already fixed the issue and sorry about letting you wait a long time. And you mentioned to provide any working example, please see the README in the project.

**Comment by heartily0421** [comment]
Thanks, very helpful.
